name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      max-parallel: 6
      matrix:
        build_platform: [x64, x86]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v6

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v3

    - name: MSBuild of plugin dll
      working-directory: .\
      run: |
        if ("${{ startsWith(github.ref, 'refs/tags/') }}" -eq "true") {
          msbuild Explorer.vcxproj /m /p:configuration="Release" /p:platform="${{ matrix.build_platform }}" /p:PlatformToolset="v143" /p:PostBuildEventUseInBuild=false /p:GitTagName=${{ github.ref_name }} /target:zip
        } else {
          msbuild Explorer.vcxproj /m /p:configuration="Release" /p:platform="${{ matrix.build_platform }}" /p:PlatformToolset="v143" /p:PostBuildEventUseInBuild=false /target:zip
        }
      shell: pwsh
      env:
        ZIPCMD: 7z a -tzip

    - name: Archive
      uses: actions/upload-artifact@v7
      with:
        name: Explorer-Release-${{ matrix.build_platform }}
        path: build\bin\${{ matrix.build_platform }}\Release\Explorer.dll

    - name: Release
      uses: softprops/action-gh-release@v3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        body: ${{ github.event.commits[0].message }}
        files: build/bin/${{ matrix.build_platform }}/Release/Explorer-${{ github.ref_name }}-${{ matrix.build_platform }}.zip
        overwrite_files: true

    - name: SHA256
      if: startsWith(github.ref, 'refs/tags/')
      run: sha256sum.exe build\bin\${{ matrix.build_platform }}\Release\Explorer-${{ github.ref_name }}-${{ matrix.build_platform }}.zip
